name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Ou outra branch que deseja usar

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Construir e enviar a imagem
        run: |
          docker build -t seu-usuario/chatwoot-4.0.3-futurize:latest .
          docker push seu-usuario/chatwoot-4.0.3-futurize:latest
